### ISSUE TITLE
Firmware Updater not opening

### ISSUE THREAD

**Issue by cristofercruz** [Cliffback/FlashGBX-macOS#2]
The **Firmware Updater** option under **Options** > **Tools** isn't loading. The popup never opens. This is with a GBxCart RW 1.4a on an M3 MacBook Air. 

I was able to get the latest L13 firmware installed using the official CLI utility.

**Comment by Piwio** [comment]
Same for me :-(

**Comment by Cliffback** [comment]
Thanks for pointing out this, I will have a look into it.

**Comment by Cliffback** [comment]
@cristofercruz and @Piwio Firmware update should work now as of this PR: #3
